### ISSUE TITLE
Release for 3.0.0-alpha?

### ISSUE THREAD

**Issue by antch** [JamesHenry/ng-custom-element#6]
Is there a possibility of a proper npm release for this version?

**Comment by JamesHenry** [comment]
I'm sorry for the delayed response, @antch.

3.0.0-alpha.0 is a release I pushed out based on a specific use-case I had. I curious why you are also interested in this - are you having issues with 2.x? Please let me know if you are

**Comment by antch** [comment]
No problem. The reason why I am using 3.0.0 is because I spoke to you at ng-conf and you recommended trying it out based on an issue I mentioned I was having. Since I started using the library I have found & reported multiple bugs in Angular Elements, so I have more clarity regarding the limitations there. It may very well be possible for me to use 2.x, may I ask which specific use-case 3.0 was meant to solve?

**Comment by antch** [comment]
Closing this -- I actually was running into an issue with the alpha version, switched to 2.0.3 and everything seems to be working fine now.
